config/routes.rb
Jokelocker3::Application.routes.draw do
  get "oauths/oauth"
  get "oauths/callback"
  root to: 'welcome#index'

  resources :jokes do
    post 'add', on: :member
    delete 'remove', on: :member
  end
  resources :user_sessions
  resources :users


  get 'signup' => 'users#new', :as => :signup
  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  get "oauth/callback" => "oauths#callback"
  post "oauth/callback" => "oauths#callback"
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  belongs_to :user
end

app/models/joke.rb
class Joke < ActiveRecord::Base
  belongs_to :creator, :class_name => "User"
  has_many :joke_collections
  has_many :users, through: :joke_collections


end

app/models/joke_collection.rb
class JokeCollection < ActiveRecord::Base
  belongs_to :user
  belongs_to :joke
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery! do |config|
    config.authentications_class = Authentication
  end

  validates :password, length: { minimum: 3 }
  validates :password, confirmation: true
  validates :password_confirmation, presence: true

  validates :email, uniqueness: true
  validates :username, uniqueness: true

  has_many :joke_collections
  has_many :jokes, through: :joke_collections

  has_many :authentications, :dependent => :destroy
  accepts_nested_attributes_for :authentications
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/joke_collection_controller.rb
class JokeCollectionController < ApplicationController
  def new
  end

  def create

  end

  
end

app/controllers/jokes_controller.rb
class JokesController < ApplicationController
  def index
    if current_user
      @jokes = Joke.all
    else
      redirect_to :root
    end
  end

  def new
    @joke = Joke.new
  end

  def create
    @joke = Joke.new(joke_params)
    @joke.creator_id = current_user.id
    if @joke.save
      # @joke.joke_collections.build (Why didn't this work?)
      current_user.jokes << @joke
      # JokeCollection.create(user_id: current_user.id, joke_id: @joke.id)
      redirect_to jokes_path
    else
      render 'new'
    end
  end

  def show
    @joke = Joke.find(params[:id])
  end

  def destroy
    @joke = Joke.find(params[:id])
    @joke.destroy
    JokeCollection.where(:joke_id => params[:id]).destroy_all
    redirect_to jokes_path
  end

  def add
    @joke = Joke.find(params[:id])
    current_user.jokes << @joke
    redirect_to user_path(current_user)
  end

  def remove
    @joke = Joke.find(params[:id])
    current_user.joke_collections.find_by_joke_id(@joke.id).delete
    redirect_to user_path(current_user)
  end

  private
  def joke_params
    params.require(:joke).permit(:title, :punchline, :format)
  end
end

app/controllers/oauths_controller.rb
class OauthsController < ApplicationController
  skip_before_filter :require_login
  
  def oauth
    login_at(params[:provider])
  end

  def callback
    provider = params[:provider]
    if @user = login_from(provider)
      redirect_to root_path, :notice => "Logged in from #{provider.titleize}!"
    else
      begin
        @user = create_from(provider)
        # NOTE: this is the place to add '@user.activate!' if you are using user_activation submodule

        reset_session # protect from session fixation attack
        auto_login(@user)
        redirect_to root_path, :notice => "Logged in from #{provider.titleize}!"
      rescue
        redirect_to root_path, :alert => "Failed to login from #{provider.titleize}!"
      end
    end
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    if @user = login(params[:username], params[:password])
      redirect_back_or_to(:jokes, notice: 'Login successful')
    else
      flash.now[:alert] = "Login failed"
      render action: "new"
    end
  end

  def destroy
    logout
    redirect_to(:root, notice: 'Logged out!')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to jokes_path
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @jokes = @user.jokes
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to user_path
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to 'welcome#index'
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if current_user
      redirect_to :jokes
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/joke_collection_helper.rb
module JokeCollectionHelper
end

app/helpers/jokes_helper.rb
module JokesHelper
end

app/helpers/oauths_helper.rb
module OauthsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/jokes/_knockform.html.erb
<%= form_for @joke do |f| %>
  <h1>Knock Knock</h1>
  <h2 class="subheader">who's there?</h2>
  <%= f.text_field :title %>
  <h2 class="subheader" id="who"><span id="knocksetup"> </span>who?</h2>
  <%= f.text_field :punchline %>
  <%= f.hidden_field(:format, value: "knock") %>
  <%= f.button %>
  <%= link_to "<button>Cancel</button>".html_safe, root_path %>
<% end %>

app/views/jokes/_oneliner_form.html.erb
<h2>Lay it on me:</h2>
<%= form_for @joke do |f| %>
  <h3 class="subheader">Set Up:</h3>
  <%= f.text_field :title %>
  <h3 class="punchline">Punchline:</h3>
  <%= f.text_area :punchline %>
  <%= f.hidden_field(:format, value: "oneliner") %>
  <%= f.button %>
  <%= link_to "<button>Cancel</button>".html_safe, root_path %>
<% end %>

app/views/jokes/index.html.erb
<div class="row">  
  <div class="small-12 columns" id="jokes_head">
    <h1>All Jokes</h1>
  </div>
  <div class="row">
  <div class="small-12 columns" id="index_buttons">
      <%= link_to "Add New Joke".html_safe, new_joke_path, class: "small button" %>
      <%= link_to "My Jokes".html_safe, "/users/#{current_user.id}", class: "small button" %>
  </div>
</div>
</div>
  <% @jokes.each do |joke| %>
<div class="row">
  <div class="small-12 columns">
    <div class="panel"><%= link_to joke.title, "/jokes/#{joke.id}" %></div>
  </div>
</div>
<% end %>

app/views/jokes/new.html.erb
<div class="row">
  <div class="small-12 column" id="add_buttons">
    <button id="knock" class="small">Knock Knock</button>
    <button id="oneliner" class="small">One Liner</button>
  </div>
</div>

<div class="row">
  <div class="small-12 column" id="jokeprompt">
    <h1>What kind of joke are you telling?</h1>
  </div>
</div>

<div class="row">
  <div class="small-12 column" id="knockform">
    <%= render 'knockform' %>
  </div>
</div>

<div class="row">
  <div class="small-12 column" id="oneliner_form">
    <%= render 'oneliner_form' %>
  </div>
</div>

app/views/jokes/show.html.erb
<% if @joke.format == "knock" %>
<div class="knockknock">  
  <div class="row knock">
    <div class="small-12 columns">
      <h1 id="knock-knock">Knock Knock</h1>
    </div>
  </div>
    <div class="row whosthere">
      <div class="small-12 columns">
        <h2 class="subheader">Who's there?</h2>
      </div>
    </div>
    <div class="row">
      <div class="small-12 columns">
        <h2 class="knock-setup"><%= @joke.title %></h2>
      </div>
    </div>
    <div class="row">
      <div class="small-12 columns">
        <h2 class="subheader knock-who"><%= @joke.title + " who?" %></h2>
      </div>
    </div>
    <div class="row knockpunch">
      <div class="small-12 columns">
        <h2><%= @joke.punchline %></h2>
      </div>
    </div>
</div>
<% elsif @joke.format == "oneliner" %>
  <div class="row">
    <div class="small-12 columns setup">
      <h1><%= @joke.title %></h1>
    </div>
  </div>
  <div class="row">
    <div class="small-12 columns punchline">
      <h2 class="subheader"><%= @joke.punchline %></h2>
    </div>
  </div>
<% end %>

<div class="row submitted_by">
  <div id="small-12 columns">
    <% if @joke.creator_id? %>
    <h6>Submitted by: <%= User.find(@joke.creator_id).username %></h6>
    <% end %>
  </div>

<div class="row">
    <div class="small-12 columns" id="show_buttons">
      <%= link_to "Back to Jokes", jokes_path, class: "small button" %>
      <% if @joke.creator_id == current_user.id %>
      <%= link_to "Delete Joke", @joke, :confirm => "Are you sure you want to delete this joke?", :method => :delete, class: "small button" %>
      <% end %>
      <% if current_user.joke_collections.find_by_joke_id(@joke.id).present? %>
        <%= link_to "Remove from Collection", remove_joke_path(@joke), :method => :delete, class: "small button" %>
      <% else %>
        <%= link_to "Add to Collection", add_joke_path(@joke), method: :post, class: "small button" %>
      <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "JokeLocker" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="top-bar small" data-topbar >
      <ul class="title-area">
        <li class="name">
          <h1><%= link_to "JokeLocker", root_path %></h1>
        </li>
      </ul>

      <section class="top-bar-section">
        <% if current_user %>
        <ul class="right">
          <li class="has-dropdown">
            <a href="/users/<%= current_user.id %>"><%= current_user.username %></a>
            <ul class="dropdown">
              <li>
                <%= link_to "Logout", :logout, method: :post %>
              </li>
            </ul>
          </li>
        </ul>
        <% else %>
        <ul class="right">
          <li class="active">
            <%= link_to "Sign Up", new_user_path %>
          </li>
          <li>
            <%= link_to "Login", :login %>
          </li>
        </ul>
        <% end %>
      </section>
    </nav>
    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/oauths/callback.html.erb
<h1>Oauths#callback</h1>
<p>Find me in app/views/oauths/callback.html.erb</p>

app/views/oauths/oauth.html.erb
<h1>Oauths#oauth</h1>
<p>Find me in app/views/oauths/oauth.html.erb</p>

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post do %>
  <div class="field">
    <%= label_tag :username %><br />
    <%= text_field_tag :username %>
  </div>
  <div class="field">
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </div>
  <div class="actions">
    <%= submit_tag "Login" %>
  </div>
<% end %>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<h1>Login</h1>

<%= render 'form' %>

<%= link_to 'Back', user_sessions_path %>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>

app/views/users/show.html.erb
<div class="row">
  <div class="small-12 column" id="locker_head">
    <h1><%= current_user.username %>'s Jokes</h1>
      <div class="row">
        <div class="small-12 columns">
          <%= link_to "Browse Jokes", jokes_path, class: "small button" %>
          <%= link_to "Add New Joke", new_joke_path, class: "small button" %>
        </div>
      </div>
  </div>
</div>

  <% @jokes.each do |joke| %>
<div class="row">
  <div class="small-12 columns">
    <div class="panel"><%= link_to joke.title, "/jokes/#{joke.id}" %></div>
  </div>
</div>
<% end %>

app/views/welcome/index.html.erb
<div class="row">
  <div class="small-12 column">
    <h2 class="subheader">Discover and share your favourite party jokes.<br />Be hilarious.</h2>
    
    <h1><%= link_to "Login", :login %> or <%= link_to "Sign Up", :signup %></h1>
    <h2><%= link_to 'Login with Facebook', auth_at_provider_path(:provider => :facebook) %></h2>
  </div>
</div>